#Database
MYSQL_USERNAME: root
MYSQL_PASSWORD: somenewpassword123

#Server
CONTAINER_PORT: 8080
ACTIVE_PROFILE: dev

#Email_Cpnfig
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_USERNAME: nguyenkhanhdu956@gmail.com
EMAIL_PASSWORD: qevc rkep axxq ktbs
VERIFY_EMAIL_HOST: http://localhost:8080