spring:
  client:
    port: ${CLIENT_PORT}
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  application:
    name: medicare
  data:
    redis:
      host: redis-16806.c302.asia-northeast1-1.gce.redns.redis-cloud.com
      port: 16806
      password: URMRVHZau0HchoxCPGejcvTTf2idJEPq
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medicare
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 1000MB
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          write:
            timeout: 10000
          connection:
            timeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: ${VERIFY_EMAIL_HOST:8080}

server:
  port: ${CONTAINER_PORT:8080}
  error:
    path: /user/error
    whitelabel:
      enabled: false