#Database
MYSQL_USERNAME: root
MYSQL_PASSWORD: somenewpassword123

#Server
CONTAINER_PORT: 8080
ACTIVE_PROFILE: dev

#Email_Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_USERNAME: nguyenkhanhdu956@gmail.com
EMAIL_PASSWORD: egfl kthz udxk awbf
VERIFY_EMAIL_HOST: http://localhost:${CONTAINER_PORT}

#Port
CLIENT_PORT: 5173