#Database
MYSQL_USERNAME: root
MYSQL_PASSWORD: Crossfire123

#Server
CONTAINER_PORT: 8080
ACTIVE_PROFILE: dev

#Email_Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_USERNAME: nguyenkhanhdu956@gmail.com
EMAIL_PASSWORD: egfl kthz udxk awbf
VERIFY_EMAIL_HOST: http://localhost:${CONTAINER_PORT}

#Port
CLIENT_PORT: 5173

PAY_URL: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
TMN_CODE: H6C4OH4A
SECRET_KEY: 65H312OPIOELDF6XORMCKXYKLF4NJX6G
RETURN_URL: http://localhost:8080/api/user/payment/vn-pay-callback
VERSION: 2.1.0
COMMAND: pay
ORDER_TYPE: 270000